### ISSUE TITLE
Curseforge

### ISSUE THREAD

**Issue by Madis0** [Jerozgen/LanguageReload#2]
Please consider uploading to Curseforge as well for better discoverability and easier modpack inclusion.

**Comment by Jerozgen** [comment]
Language Reload was uploaded to Curseforge the same day that the mod was released. I'm waiting for approving by a moderator now.

**Comment by Jerozgen** [comment]
The mod has been approved:
https://www.curseforge.com/minecraft/mc-mods/language-reload
