### ISSUE TITLE
Can't use multilingual search with english and french

### ISSUE THREAD

**Issue by Pinguchi** [Jerozgen/LanguageReload#24]
I'm french and I saw the "multilingual search" option, so I wanted to be able to search items in French while still having the game in English. I can't move English to the top bcs his position is locked. Then, I tried to enable French language and did shift + F3 + J to switch language but when language switch, French language is disabled so I can't search in French.

Do you have a solution ? Ty :)

(Sry I'm french and I don't have a very good english :/ )

**Comment by Jerozgen** [comment]
Move English (United Kingdom) or any other English above French.
![Selected English (Canada), French, English (US)](https://user-images.githubusercontent.com/17567951/208304862-7c20eda5-078e-4ef5-9748-8653a5b62588.png)

**Comment by Pinguchi** [comment]
Ty :)
