### ISSUE TITLE
crashes when I try to enter the menu to change the language 1.19.2

### ISSUE THREAD

**Issue by papillo12** [Jerozgen/LanguageReload#28]
[crash-2023-01-04_20.52.44-client.txt](https://github.com/Jerozgen/LanguageReload/files/10348954/crash-2023-01-04_20.52.44-client.txt)

[latest.log](https://github.com/Jerozgen/LanguageReload/files/10348957/latest.log)

**Comment by ChromaPIE** [comment]
The problem seems solvable by a mod [here](https://github.com/Dubhe-Studio/BugJump/actions/runs/4283892887)

**Comment by Jerozgen** [comment]
I think that's a vanilla bug with fastutil. As suggested, try using [BugJump](https://modrinth.com/mod/bugjump)
