### ISSUE TITLE
Creative search does not use the language

### ISSUE THREAD

**Issue by Madis0** [Jerozgen/LanguageReload#3]
Reproduce:

1. Create a fresh Fabric profile with Fabric API and Language Reload
2. Run the profile and select any language
3. Create a world with cheats enabled, use /gamemode creative
4. Try the search on creative menu

Expected:
The search to find items by the selected language

Actual:
The search works in English, even though the item names are translated

Edit: this commit of a similar mod might help: https://github.com/ChachyDev/lazy-language-loader/commit/029aafb5def8fa4d2f23b3d16801648c2381882f

**Comment by Jerozgen** [comment]
Fixed in [Language Reload 1.2](https://github.com/Jerozgen/LanguageReload/releases/tag/v1.2). Curseforge version is currently under review.
