### ISSUE TITLE
1.19.4 support

### ISSUE THREAD

**Issue by ViTulyankin** [Jerozgen/LanguageReload#33]
Basically the title. Great mod, btw

**Comment by Jerozgen** [comment]
The mod already supports 1.19.4. Download links: [Modrinth](https://modrinth.com/mod/language-reload/version/1.5.5+1.19.4), [CurseForge](https://www.curseforge.com/minecraft/mc-mods/language-reload/files/4434815), [GitHub](https://github.com/Jerozgen/LanguageReload/releases/tag/1.5.5%2B1.19.4)

**Comment by ViTulyankin** [comment]
Sorry im really blind
