### ISSUE TITLE
Can't go through blocks in spectator mode

### ISSUE THREAD

**Issue by BBaoVanC** [Jerozgen/LanguageReload#38]
Weird but for some reason with this mod version 1.5.5 on 1.19.4 installed, I can't go through blocks in spectator mode. They act solid like other gamemodes.

**Comment by Jerozgen** [comment]
Can't reproduce

https://github.com/Jerozgen/LanguageReload/assets/17567951/74c69288-4b2d-46b4-8c8a-221aeee23d6d

**Comment by BBaoVanC** [comment]
Weird issue, for some reason it happened to not have that issue once while testing without this mod, but now it's happening even on vanilla
