### ISSUE TITLE
Incompatible mixin for `LanguageOptionsScreen#keyPressed`

### ISSUE THREAD

**Issue by Antikyth** [Jerozgen/LanguageReload#44]
I am not a user of Language Reload, but I was alerted to this problem by [this issue on my own mod's repo](https://github.com/Antikyth/searchable/issues/23).  Language Reload has a number of overrides for methods in that mixin instead of actually doing some kind of compatible injection.

It seems that in the case of `LanguageOptionsScreen#keyPressed`, both our mods - mine being [Searchable](https://github.com/Antikyth/searchable) - mix into `keyPressed` with the same purpose: to allow our search boxes to be typed in, due to a mistake in vanilla where they seem to have accidentally overridden `keyPressed` in `LanguageOptionsScreen` instead of `LanguageListWidget`.

I opted to solve this by using [Mixin Extras' `ModifyExpressionValue`](https://github.com/LlamaLad7/MixinExtras/wiki/ModifyExpressionValue) (Mixin Extras can be bundled with this mod without adding more dependencies for users) to add a check that the language list is selected to the method call named `CommonInputs.isToggle(keyCode)` in Quilt Mappings in a way that is compatible with other mods adding the same or other conditions.  I think that is probably a reasonable solution for your mod too.

This is the mixin Searchable uses if you wanted to use it for reference:
```java
// Only select a language when a toggle key is pressed if the language selection list is focused.
@ModifyExpressionValue(method = "keyPressed", at = @At(
    value = "INVOKE",
    target = "Lnet/minecraft/client/gui/CommonInputs;isToggle(I)Z"
))
private boolean onlySelectLanguageIfFocused(boolean original) {
    // Only if the language selection list is focused...
    return original && this.languageSelectionList.equals(this.getFocused());
}
```

**Comment by Jerozgen** [comment]
The crash should be fixed in 1.5.9
