### ISSUE TITLE
latest version doesnt work with quilt

### ISSUE THREAD

**Issue by Arach-Knight** [Jerozgen/LanguageReload#60]
![image](https://github.com/Jerozgen/LanguageReload/assets/127950331/002ae6d9-bd02-492d-ab71-44304bc76582)

**Comment by Jerozgen** [comment]
I've uploaded a new version of Language Reload 1.5.11+1.20.6 with a changed dependency requirement. For Minecraft versions 1.20.4 and below, please use LR 1.5.10 at the moment
