### ISSUE TITLE
Use assets/minecraft/textures/gui/sprites/transferable_list textures

### ISSUE THREAD

**Issue by TrigamDev** [Jerozgen/LanguageReload#61]
8 of the 9 textures the mod includes are used for the directional buttons for the language selection screen. However, all of these are direct duplicates of existing Minecraft textures.
- `assets/minecraft/textures/gui/sprites/transferable_list/select.png`
- `assets/minecraft/textures/gui/sprites/transferable_list/select_highlighted.png`
- `assets/minecraft/textures/gui/sprites/transferable_list/unselect.png`
- `assets/minecraft/textures/gui/sprites/transferable_list/unselect_highlighted.png`
- `assets/minecraft/textures/gui/sprites/transferable_list/move_down.png`
- `assets/minecraft/textures/gui/sprites/transferable_list/move_down_highlighted.png`
- `assets/minecraft/textures/gui/sprites/transferable_list/move_up.png`
- `assets/minecraft/textures/gui/sprites/transferable_list/move_up_highlighted.png`

Using the existing transferable list textures would increase consistency and make it so resource packs that already change the vanilla ones change the mod's buttons, too.

**Comment by Jerozgen** [comment]
These textures are actually different. I'm not going to use the vanilla ones

![select](https://github.com/Jerozgen/LanguageReload/assets/17567951/259a9dbf-d284-47f7-8cc6-d347e9fa60a2)

![move_up](https://github.com/Jerozgen/LanguageReload/assets/17567951/52df7df3-239c-41be-b89f-1085a6cf5acc)
