### ISSUE TITLE
Creative search does not use the language

### ISSUE THREAD

**Issue by Disguys** [Jerozgen/LanguageReload#8]
Every time I launch Minecraft, I can't use creative search until I press the F3+J keyboard shortcut, every time I restart Minecraft, the search for items using the language in Creative mode lost.

Minecraft 1.18.2
LanguageReload v1.2.1

Video: https://youtu.be/JNGyf6qDV3g

[This problem is similar to mine, but it's a little different.](https://github.com/Jerozgen/LanguageReload/issues/3)

**Comment by Jerozgen** [comment]
That's actually a Dash Loader bug.

https://user-images.githubusercontent.com/17567951/174054882-558b567b-892c-45d4-b3e2-88a85482a0e5.mp4

**Comment by Disguys** [comment]
Ohh, okay, thanks
